
name: b
on:
  workflow_run:
    workflows: ["a"]
    branches: [main]
    types: 
      - completed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow B"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"


