name: c
on:
  workflow_run:
    workflows: ["b"]
    types: 
      - completed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow C"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
