name: d
on:
  workflow_run:
    workflows: ["c"]
    types: 
      - completed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow D"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
