name: e
on:
  workflow_run:
    workflows: ["d"]
    branches: [main]
    types: 
      - completed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow E"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
