name: f
on:
  workflow_run:
    workflows: ["e"]
    branches: [main]
    types: 
      - completed
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "workflow F"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
